
version: '3'
services:
  
  app:
    build: app/.
    depends_on:
      - db

    environment:
     - API_IDENTIFIER=https://XXXXX
     - AUTH0_DOMAIN=XXXXX.XX.auth0.com
     - ALGORITHMS=RS256
     - CLIENT_ID=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     - CLIENT_SECRET=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
     - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://postgres:password@db/data
     - APP_SECRET_KEY=XXXXXYYYYY
     - SQLALCHEMY_TRACK_MODIFICATIONS=True

  db:
    container_name: db
    image: postgres:9.6.8
    restart: always
    volumes:
      -  /tmp/pgdata/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  www:
    restart: always
    build: nginx/.
    links:
      - app
    depends_on:
      - app
    ports:
      - "80:80"
